### PR TITLE
Add an API to the mod

### PR DESCRIPTION
**Pull request by ichttt**
Hello CreativeMD,
I am submitting this patch because I need the API to make your mod compatible with my FirstAid mod.

Briefly tested and behaves normal as expected.

### CODE REVIEW

**Comment by CreativeMD** [comment]
WOW! That's amazing, will release it right now. Thank you very very much! I was already thinking of adding your mod (FirstAid) to my modpack.

BTW about EnhancedVisuals, if you have any suggestions of what kind of effects i could add just let me know.

**Comment by ichttt** [comment]
@CreativeMD sure, I'll ping you. As for EnhancedVisuals, I'll think about it.

**Comment by ichttt** [comment]
FirstAid integration for this mod is done and version published on CurseForge(1.3.3).

**Comment by CreativeMD** [comment]
Ok added it, sorry that it took so long, i have been quite busy unfortunately.

**Pull request merged**
